// Copies compiled ABIs from the Foundry build into src/abi.ts.
// Run `forge build` in ../contracts first.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../src/abi.ts");

const load = (name) =>
  JSON.parse(readFileSync(join(here, `../../contracts/out/${name}.sol/${name}.json`), "utf8")).abi;

const registry = load("DirectiveRegistry");
const controller = load("PassportController");

writeFileSync(
  out,
  `// Generated by scripts/abi.mjs from contracts/out. Do not edit.\n` +
    `export const registryAbi = ${JSON.stringify(registry, null, 2)} as const;\n\n` +
    `export const controllerAbi = ${JSON.stringify(controller, null, 2)} as const;\n`,
);
console.log(`wrote ${out} (registry ${registry.length}, controller ${controller.length} entries)`);
