// Copies the compiled ABI from the Foundry build into src/abi.ts.
// Run `forge build` in ../contracts first.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const artifact = join(here, "../../contracts/out/DirectiveRegistry.sol/DirectiveRegistry.json");
const out = join(here, "../src/abi.ts");

const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
writeFileSync(
  out,
  `// Generated by scripts/abi.mjs from contracts/out. Do not edit.\nexport const registryAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
console.log(`wrote ${out} (${abi.length} entries)`);
